### PR TITLE
Change back to return Array

### PR DESCRIPTION
**Pull request by FrankYFTang**

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@anba

**Comment by FrankYFTang** [comment]
address https://github.com/tc39/proposal-intl-enumeration/issues/23

**Review by ljharb — APPROVED** [review]

**Review by ryzokuken — APPROVED** [review]

**Review by anba — APPROVED** [review]
LGTM! Thanks. :+1:

**Comment by FrankYFTang** [comment]
be aware the "return array" approach save the implementation from coding a special iterator object which not only reduce the implementation complexity but also reduce the necessary compiled code because we could just reuse the array object w/o special class or data type in C++. Iterator approach would benefit for classes require expensive computation if most of the information may not needed later. But for this case, there are no expensive computation involved and the trade of memory is not necessary net beneficial due the requirement of special case code for the iterator object.

**Review by sffc — COMMENTED** [review]
Thanks for sharing your findings with regard to memory savings for not needing the additional primordial type.

**Pull request merged**
